### ISSUE TITLE
Add login/register authentication using next-auth

### ISSUE THREAD

**Issue by ZaidMarrie** [ZaidMarrie/ethereal-fashion-store#17]
## Overview

Add authentication using the `next-auth` library. Login, logout, and register should use existing routes within the application. The forms for these routes are already built, and they have Google, and Facebook as login providers. 

**Tasks:**

- [ ] Add authentication to login using email and password
- [ ] Add authentication to register using email and password
- [ ] Add Google authentication provider
- [ ] Add Facebook authentication provider
